services:
  repeater:
    image: repeater
    container_name: repeater_web
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./examples:/app/examples
      #- ./examples:/app/jobs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /tmp/repeater:/tmp/repeater
    environment:
      REPEATER_JOBS_DIRECTORY: /app/examples
      REPEATER_LOGS_DIRECTORY: /tmp/repeater
      #REPEATER_PASSWORD: "qwerty"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: repeater_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_repeater:/var/lib/clickhouse
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      CLICKHOUSE_USER: chuser
      CLICKHOUSE_PASSWORD: password123
      CLICKHOUSE_DB: repeater

  chui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: repeater_chui
    restart: always
    ports:
      - "8001:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123"
      VITE_CLICKHOUSE_USER: "chuser"
      VITE_CLICKHOUSE_PASS: "password123"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  streamlit:
    image: streamlit
    container_name: repeater_streamlit
    build:
      context: ./examples
      dockerfile: ./Dockerfile_streamlit
    ports:
      - "8002:8501"
    volumes:
      - ./examples/streamlit.py:/app/streamlit.py:ro
      - ./examples/connections.py:/app/connections.py:ro

volumes:
  clickhouse_repeater:
